.vscode/settings.json, closest-value-bst.py, depth-first-search.py
Merge Depth First Search algorithm with unit test to master branch.
=> Closest value bst

nth-fibonacci.py
Created nth Fibonacci algorithm with unit tests. The algorithm is the most efficient way to calculate the nth Fibonacci, costing O(n) in time and O(1) in space.
=> Created nth Fibonacci algorithm with unittests.

nth-fibonacci.py
Correct case n = 1 for the nth Fibonacci algorithm and add a unit test to cover it.
=> Correct case n = 1 and add unit test for it

product-sum.py
Create product sum algorithm with its unit tests and add information about the computational cost in time and space.
=> Product sum

binary-search.py
Create function that takes in a sorted array of integers as well as a target integer and using the binary search algorithm determines if the target integer is contained in the array. It returns its index if the target is found and -1 if not.
Unit tests have been included.
=> feat: Create Binary Search algorithm

find_three_largest_numbers.py
Create an algorithm that takes in an array of at least three integers and, without sorting the input array, returns a sorted array of the three largest integers in the input array.
The function should return duplicate integers if necessary; for example, it should return [10, 10, 12] for an input array of [10, 5, 9, 10, 12].
Include unit tests to verify the implementation.
=> feat: Three Largest Numbers

bubble_sort.py
It takes in an array of integers and returns a sorted
version of that array using the Bubble Sort algorithm.
=> feat: bubble sort algorithm

insertion_sort.py
It takes in an array of integers and returns a sorted version
of that array using the Insertion Sort algorithm
=> feat: insertion sort algorithm

caesar_cypher_encryptor.py
Given a non-empty string of lower case letters and a
non-negative integer representing a key, the function
returns a new string obtained by shifting every letter
in the input string by k positions in the alphabet, where
k is the key.
=> feat: caesar cypher encryptor

three_num_sum.py
It takes in a non-empty array of distinct integers and an integer
representing a target sum. The function finds all triplets in the
array that sum up to the target sum and return a two-dimensional array of all these triplets. 
The numbers in each triplet are ordered in ascending order, and the triplets themselves are 
ordered in ascending order with respect to the numbers they hold.
They function returns an empty array if no three numbers sum up to the target sum.
=> feat: three number sum

smallest_difference.py
Take in two non-empty arrays of integers, find the pair of numbers (one from each array) 
whose absolute difference is closest to zero, and return an array containing those two
numbers, with the number from the first array in the first position.
Assume there will be only one pair of numbers with the smallest difference.
=> feat: smallest difference algorithm

move_element_to_end.py
Given an array of integers and an integer, the algorithm moves all instances of that integer in the array to the end of the array and returns the array.
The function performs this in place (i.e. it mutates the input array).
=> feat: move element to end algorithm

monotonic_array.py
Takes in an array of integers and returns a boolean representing whether the array is monotonic.
An array is said to be monotonic if its elements, from left to right, are entirely non-increasing or entirely non-decreasing.
=> feat: monotonic array algorithm

Medium/bst_traversal.py
Three functions that take in a Binary Search Tree (BST) and an empty array, traverse the BST, add its nodes' values to the input array, and return that array. The three functions traverse the BST using the in-order, pre-order and post-order tree-traversal techniques, respectively.
=> feat: bst traversal algorithm

Medium/min_height_bst.py
Takes in a non-empty sorted array of distinct integers, constructs a BST from the integers, and return the root of the BST.
It minimizes the height of the BST.
=> feat: min height bst algorithm

Medium/max_subset_sum_no_adjacent.py
Takes in an array of positive integers and returns the maximum sum of non-adjacent elements in the array.
If the sum can't be generated, the function returns 0.
=> feat: max subset sum no adjacent algorithm + unit tests

Medium/number_ways_make_change.py
Given an array of distinct positive integers representing coin denominations and a single non-negative integer n representing a target amount of money, the function returns the number of ways to make change for that amount using the given coin denominations.
An unlimited amount of coins is at our disposal.
=> feat: add number of ways to make change algorithm

Medium/min_number_coins_change.py
Given an array of positive integers representing coin denominations  and a single non-negative integer n representing a target amount of money, write a function that returns the smallest number of coins needed to make change for (to sum up to) that target amount  using the given coin denominations.
You have an unlimited amount of coins.If it's impossible to make change for the target amount, return -1.
=> feat: structure of min number of coins for change algo

Medium/levenshtein_distance.py
Takes in two strings and returns the minimum number of edit operations that need to be performed on the first string to obtain the second string.
There are three edit operations: insertion of a character, deletion of a character, and substitution of a character for another.
=> feat: levenshtein distance algo

Medium/kadanes_algorithm.py
Takes in a non-empty array of integers and returns the maximum sum that can be obtained by summing up all of the integers in a non-empty subarray of the input array. A subarray must only contain adjacent numbers.
=> feat: kadane's algorithm
